# -*- coding: utf-8 -*-
"""
/***************************************************************************
 numeros_exteriores
                                 A QGIS plugin
 Este plugin otorga herramientas para los trabajos del area de cartografia referente a los numeros exteriores
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-25
        copyright            : (C) 2023 by INE, Direccion de Cartografia Electoral, Saul Valencia
        email                : luissaul.valencia@ine.mx
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load numeros_exteriores class from file numeros_exteriores.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .numeros_exteriores import numeros_exteriores
    return numeros_exteriores(iface)
